### ISSUE TITLE
Make DTO class definitions easier to identify in the codebase

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#165]
This came out of a video call that @KacperKluka, @owenpearson and myself had today.

We were discussing conforming the [JS SDK](https://github.com/ably/ably-asset-tracking-js) API with the one in this repository, including where that might intersect with the schemas in the [common repository](https://github.com/ably/ably-asset-tracking-common). Owen pointed out that it wasn't entirely clear to him whether [EnhancedLocationUpdateMessage](https://github.com/ably/ably-asset-tracking-android/blob/1251ad4a24193875322ea971758f1a135e9c1a68/common/src/main/java/com/ably/tracking/common/MessageModels.kt#L37) was a [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) or not.

This is quite an interesting observation to me. While these classes will often be `internal` to the project they're defined in, they end up being exposed externally as part of the wider ecosystem.

A number of approaches come to mind, roughly in order of lightness of touch:

1. Put something in the class commentary
2. Decorate all DTO class definitions with an [annotation](https://kotlinlang.org/docs/reference/annotations.html)
3. Add `Dto` or similar suffix to class names
4. Move all DTO class definitions to a common package - e.g. `com.ably.tracking.common.dto`

My preference would be (2), because:

- problems with (1) are that it's prone to human error, being forgotten or going out of sync
- a problem with (3) is that it adds superfluous noise to sites of use (e.g. invocations of constructor)
- a problem with (4) is that it potentially moves the DTO definitions further away from where they should be naturally defined - unless we end up having multiple `dto` nodes in various packages throughout the codebase

Also, with option (2) there's the potential for us to add properties to the annotation which could be useful in testing and/or compliance verification later on. e.g. a pointer to schema in use.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-230) by [Unito](https://www.unito.io/learn-more)

**Comment by KacperKluka** [comment]
I think we should wait with this issue until https://github.com/ably/ably-asset-tracking-android/issues/271 is closed.
