### ISSUE TITLE
Decide whether we should use battery level when comparing LocationUpdate objects

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#210]
As noticed in [this comment](https://github.com/ably/ably-asset-tracking-android/pull/150/files#r592610283) we're ignoring battery level when comparing `LocationUpdate` objects. We should decide if that's the correct way of comparing those objects.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-273) by [Unito](https://www.unito.io/learn-more)

**Comment by kavalerov** [comment]
This is actually a good question. What is the main use of comparison? From "philosophical" point of view, location updates with different battery are different - as in they were definitely generated separately.

**Comment by KacperKluka** [comment]
I think that we're only comparing them in our integration tests :wink: 
I'd say that we should use the battery level when comparing them because it's an integral part of the whole location update.
