### ISSUE TITLE
Handle exception thrown when sending enhanced location update fails

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#213]
As noticed in [this comment](https://github.com/ably/ably-asset-tracking-android/pull/193/files#r592935320), we should decide how to handle an exception thrown when sending an enhanced location update fails.

We could try to cache that failed location and try to resend it later (i.e. when Ably is reconnected). But this only makes sense if we're able to send it before the next location update is received, so it would be a rather complicated solution. But it will be useful if we'll need to care about having the complete history of the location events (i.e. for a dashboard or something like that).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-781) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@kavalerov After landing https://github.com/ably/ably-asset-tracking-android/issues/66 we have now `skippedLocations` as a part of the location update message. Maybe we should simply add the locations that failed to those skipped locations list? Would that be okay or are you worried that we will mix location updates skipped due to the resolution with location updates that weren't sent because of some errors? :thinking:

**Comment by KacperKluka** [comment]
We've decided on today's call that we will add those lost location updates to the `skippedLocations` list and send them in chronological order (sorted by location timestamp) whenever the network is available (with the next location update). 
We should define the maximum size of the failed locations list so we don't end up with an enormous list of unsent locations. If the failed locations list gets full then we will keep removing the oldest location updates in order to make place for the newest ones. Once we successfully send the failed locations the list will be cleared.

In order to fix it, we will need to use the asynchronous version of the `publish()` method to know exactly if sending a location failed since the Ably SDK tries to resend the message before giving up and reporting an error.

**Comment by KacperKluka** [comment]
On today's call, we've agreed that since `skippedLocations` is a kind of a "luxury feature" and because preserving its state after introducing the asynchronous version of the `publish()` method becomes quite tricky, we should be fine with trying to send it only once and if that sending fails then that `skippedLocations` data is lost.
Given above we should clear the `skippedLocations` list when we're sending it.

**Comment by paddybyers** [comment]
I wasn't part of this discussion but I'd like to understand the reasoning.
