### ISSUE TITLE
Update Mapbox dependency to Nav 2.0

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#225]
Mapbox have just released  a new version of their SDK: https://www.mapbox.com/blog/on-device-routing-flexible-and-versatile-camera-mapbox-navigation-sdk-v2

The part that is relevant to us is lower battery and network consumptions. 

We need to asses wether it introduces any breaking changes to our integration, and update the dependency.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-287) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
Relates to https://github.com/ably/ably-asset-tracking-cocoa/issues/106.
