### ISSUE TITLE
Handle stopped state of the Subscriber

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#227]
We should add logic to the Subscriber that will handle it in its stopped state. This most likely means that any call to the Subscriber API will result in an exception being thrown (something like `SubscriberStoppedException`). In case of someone calling the `stop()` method we should return success instead of a failure.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-291) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
I agree with your initial proposal, @KacperKluka ... I think this issue is ready to implement.
