### ISSUE TITLE
Check if we should pass client ID when using the AblySimulationLocationEngine

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#232]
Currently, we're only passing the Ably API key when creating the `AblySimulationLocationEngine` and we're not passing any client ID. We should check if that's okay to not pass the client ID.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-784) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
I think a valid question would also be whether there should be a discrete client id that is supplied just for use by the simulation engine.

The `TODO` statement to which this issue pertains is [here](https://github.com/ably/ably-asset-tracking-android/blob/964ad4e49e1a4efab4da51c58e9513de6db7363f/publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt#L212).

**Comment by paddybyers** [comment]
I don't think the `clientId` that is used to subscribe to, or publish to, the channel for the simulated location engine are relevant at all. I would not include a `clientId` at all.

**Comment by KacperKluka** [comment]
Things have changed and now we're passing the client ID to the `AblySimulationLocationEngine`, if that's not a problem then let's close this issue, otherwise it should be changed to remove that ID from the simulation engine :wink:
