### ISSUE TITLE
Implement AppPreferences as a singleton

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#234]
We could add some lightweight DI framework (like [Koin](https://insert-koin.io/)) to the Publisher example app, for example, to inject the `AppPreferences`.
On the one hand, it might make the example app less explicit but on the other hand, DI is almost a standard in the Android world and almost everyone knows what it is and how to use it.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-786) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
A goal of the example apps is to keep them simple and explicit, so I am finding it hard to establish any enthusiasm for this proposal. Apart from anything else, @KacperKluka's opening comment doesn't really explain for me what problem we would be solving by implementing this. 🤔

**Comment by KacperKluka** [comment]
The problem is that we have multiple places in which we're creating the `AppPreferences` instances. This leads to multiple instances of Android's `SharedPreferences` being created throughout the app's lifecycle. This isn't a very big problem but it still would be better to only have one instance of the `AppPreferences`. One way to achieve that is a DI which will make sure there's only one instance of a given class. The other thing that we can do is just implement the `AppPreferences` as a singleton by ourselves.

**Comment by KacperKluka** [comment]
After giving it a second thought I think that a DI might be complicating things a bit so I'd change the `AppPreferences` to use the singleton pattern :wink:
