### ISSUE TITLE
Add a button that will focus the map on the asset location in the Subscriber example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#242]
The map in the Subscriber example app isn't following the position of a tracked asset and quite quickly the asset can disappear from the view and the user has to zoom out and try to find it, which can be annoying.
We could add a button that will focus the map on the current asset position so the user won't have to manually search for it.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-319) by [Unito](https://www.unito.io/learn-more)

**Comment by kavalerov** [comment]
Les improve this even further - make the map centred on the marker, not just "center" button.

**Comment by KacperKluka** [comment]
This was abandoned due to the automatic map centering https://github.com/ably/ably-asset-tracking-android/pull/289
