### ISSUE TITLE
Ensure we report all relevant SDK version info

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#251]
We should report ably-java version as well ably-asset-tracking-android version.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-788) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
@QuintinWillison Can you please groom the title and the description if needed?

**Comment by QuintinWillison** [comment]
Initially blocked by https://github.com/ably/docs/pull/1034.
Will then require changes to [ably-java](https://github.com/ably/ably-java) to open up an interface for this library to use in order to inject this information.

Relates to https://github.com/ably/ably-flutter/issues/94.
