### ISSUE TITLE
Document the Event classes that are used in both SDKs

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#260]
As mentioned in [this comment](https://github.com/ably/ably-asset-tracking-android/pull/224#discussion_r602023206), we should document the `Event` classes that are used in Subscriber and Publisher SDKs. The descriptions should contain where they're used for and what their arguments convey.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-790) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Thanks for creating this, @KacperKluka. I'm going to change the label on this issue as the [documentation](https://github.com/ably/ably-asset-tracking-android/labels/documentation) label was really intended for issues relating to how we document the public API. This one is more about [code-quality](https://github.com/ably/ably-asset-tracking-android/labels/code-quality).
