### ISSUE TITLE
Move internal classes to the common module

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#271]
I've noticed that we have a few classes in the `core` module that in fact belong to the `common` module. They should be moved because while they are in the `core` module they are visible to the SDK users. Those classes are:
- GeoJsonMessage
- GeoJsonGeometry
- GeoJsonProperties
- ConnectionState
- ConnectionStateChange
- ResultHandler

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-336) by [Unito](https://www.unito.io/learn-more)

**Comment by KacperKluka** [comment]
@kavalerov I've noticed that in fact, we're exposing the `GeoJsonMessage` in the `LocationHistoryData` :thinking: I have mixed feeling about this because that class is a part of our internal DTO that's sent through Ably between Publisher and Subscriber SDKs. And also that `LocationHistoryData` is meant to be used for debug/development purposes rather than for production use. But still, due to that, we're exposing something that's meant to be our internal implementation detail to the SDK users.

WDYT? Should we create another class that would only be used for that `LocationHistoryData` or should we leave the `GeoJsonMessage` exposed in our SDKs?

**Comment by kavalerov** [comment]
This is clearly two different purposes, and my gut feeling is to have separate classes so that there is a clear separation of concerns. 

However, I am wondering, do we have other similar situations in the codebase? And what was our decision in similar situations?

**Comment by KacperKluka** [comment]
Blocked until https://github.com/ably/ably-asset-tracking-android/issues/272 is closed.
