### ISSUE TITLE
Don't expose GeoJsonMessage in the API

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#272]
I've noticed that in fact, we're exposing the `GeoJsonMessage` in the `LocationHistoryData` :thinking: I have mixed feeling about this because that class is a part of our internal DTO that's sent through Ably between Publisher and Subscriber SDKs. And also that `LocationHistoryData` is meant to be used for debug/development purposes rather than for production use. But still, due to that, we're exposing something that's meant to be our internal implementation detail to the SDK users.

WDYT? Should we create another class that would only be used for that `LocationHistoryData` or should we leave the `GeoJsonMessage` exposed in our SDKs?

_Originally posted by @KacperKluka in https://github.com/ably/ably-asset-tracking-android/issues/271#issuecomment-811089641_

We should create a separate class that will hold the data for the `LocationHistoryData`.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ATS-337) by [Unito](https://www.unito.io/learn-more)

**Comment by paddybyers** [comment]
The format of the content of messages needs to be public. Customers need to be able to consume messages via means other than Subscriber connections, eg webhooks, other integrations, history etc.

If we had a need to include additional data in `LocationHistoryData` for debug purposes, then that can be a privately declared class that extends or embeds `GeoJsonMessage`.

**Comment by KacperKluka** [comment]
That sounds right but I think it doesn't mean that we need to expose that message classes in the code. If a customer needs to know the format of the messages he can either take a look at our Github repository or we can prepare some kind of a JSON Schema for the messages and put it in the README.
IMO there's no need to expose those internally used message classes in the SDKs because the SDK users won't be able to use them anyway since they're not used anywhere in our API.

**Comment by paddybyers** [comment]
I think we should discuss with Quintin. If someone receives a `GeoJSONMessage` in a webhook request body, for example, it would be useful if they could use a library to decode it. We have a similar thing already for other types in the Ably libary (eg `Message.fromEncoded()` or something like that).

**Comment by KacperKluka** [comment]
We've decided that GeoJsonMessage should be exposed and used in the location history data.
