### ISSUE TITLE
 add capability to the SDK to support JWT flow + examples

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#285]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-794) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
See https://github.com/ably/ably-asset-tracking-android/pull/222#discussion_r608561484.

**Comment by QuintinWillison** [comment]
We've only so far got Ably TokenRequest flow in the API, so this issue will involve adding the capability to the SDK to support JWT flow.
