### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#318]
Spawned from https://github.com/ably/ably-asset-tracking-android/issues/286.
See [this comment](https://github.com/ably/ably-asset-tracking-android/pull/317#issuecomment-832444187).

We've already created a project for groupId `com.ably` under [OSSRH-68447](https://issues.sonatype.org/browse/OSSRH-68447), which currently allows @paddybyers and @QuintinWillison to publish.

However, before we can publish to [Maven Central](https://mvnrepository.com/repos/central), we need to meet Sonatype's [publishing requirements](https://central.sonatype.org/publish/requirements/). This means that we need to do the following:

- [ ] Supply Sources (`-sources.jar`)
- [ ] Supply Javadoc (`-javadoc.jar`)
- [ ] Sign files with GPG/PGP - we'll use the key we already use for `ably-java`
- [ ] Populate missing metadata:
    - [ ] `name`
    - [ ] `description`
    - [ ] `url`
    - [ ] `licenses`
    - [ ] `developers`
    - [ ] `scm`

One possible Android library plugin issue we may need to work around is https://issuetracker.google.com/issues/145670440.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-806) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
"Marked as fixed" 🤔  https://issuetracker.google.com/issues/145670440?pli=1

**Comment by ikbalkaya** [comment]
There is a good tutorial out there  in this link
https://proandroiddev.com/publishing-android-libraries-to-mavencentral-in-2021-8ac9975c3e52

which makes it easy to set  Sonatype requirements. I have prepared the project roughly to consume this configuration but I will need following credentials to test my changes with minimal inputs inputs.

```
signing.keyId=5BEF072A
signing.password=signingPass123
signing.key=bm90IGEgcmVhbCBrZXksIHdoYXQgd2VyZSB5b3UgZXhwZWN0aW5n
ossrhUsername=yourSonatypeUser
ossrhPassword=yourSonatypePassword
```
I will cross check with Java project and set those values for Github Actions (not configured yet) but would be nice to test those locally.

Also it would be useful to discuss the metadata we provide. These are quickly configurable using only one file in the current structure (publish-module.gradle_

 name - Artifact ids -> I have created one for each module, they might need tweaking
 description -> I have put a generic 'Ably asset tracking library' for all, will most likely need to change
 url - I have added Asset Tracking library's Github URL
 licenses - I have linked license page on Github
 developers - We can add multiple developers here. Who should I add? Everyone involved in project?
 scm - I have not yet updated this, I will after I figure out what to put there

**Comment by ikbalkaya** [comment]
@QuintinWillison We will need to add those following secrets to Github in order to test/run the workflow

${{ secrets.OSSRH_USERNAME }}
${{ secrets.OSSRH_PASSWORD }}
${{ secrets.SIGNING_KEY_ID }}
${{ secrets.SIGNING_PASSWORD }}
${{ secrets.SIGNING_KEY }}
${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

**Comment by QuintinWillison** [comment]
@ikbalkaya I've [commented on our Sonatype project issue](https://issues.sonatype.org/browse/OSSRH-68447?focusedCommentId=1114256&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1114256) in relation to OSSRH username as I'm not comfortable using an identity tied to an individual. Let's see what they get back to us with. cc @paddybyers

**Comment by QuintinWillison** [comment]
@ikbalkaya They [got back to us](https://issues.sonatype.org/browse/OSSRH-68447?focusedCommentId=1114393&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1114393). I shall create a bot account for this with Sonatype.

**Comment by ikbalkaya** [comment]
I was just about to comment 😆

**Comment by QuintinWillison** [comment]
Technically we're still fixing this up right now so this issue should not have been closed yet.
