### ISSUE TITLE
Channel Namespace

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#327]
Currently we have a 1:1 mapping from [Trackable.id](https://github.com/ably/ably-asset-tracking-android/blob/8f8443581bf5b4726a45f338472f461c30b685f2/publishing-sdk/src/main/java/com/ably/tracking/publisher/ConfigurationModels.kt#L217) to the Ably channel name.

This could limit use cases - e.g. where persistence needs to be enabled for just the journeys tracked and not for other uses of Ably channels.

The proposed immediate fix for this is that we add a prefix of `tracking:` (where `tracking` is the namespace) to Ably channel names used by all Asset Tracking SDKs.

There is no need at this stage to offer any additional API for this feature (i.e. the namespace `tracking` will be baked into the SDK implementations).

See Ably Help Center's: [What is a channel namespace and how can I use them?](https://knowledge.ably.com/what-is-a-channel-namespace-and-how-can-i-use-them)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-810) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
What do you mean by persistence? Do you mean `Message persistence` from https://ably.com/documentation/how-ably-works. I didn't know you could this this off. Or did you mean history? Or presence? I guess its related to this page somehow:

![Screenshot 2021-05-18 at 22 30 57](https://user-images.githubusercontent.com/24711048/118726087-b8966a00-b828-11eb-8693-791f7c431f89.png)

> e.g. where persistence needs to be enabled for just the journeys tracked and not for other uses of Ably channels.

I don't understand this, can you clarify and also give another example?

Thanks

**Comment by QuintinWillison** [comment]
Thanks, @ben-xD ... Paddy responded to your subsequent question [here](https://github.com/ably/ably-asset-tracking-cocoa/pull/143#issuecomment-846357876) so I believe this is now covered.
