### ISSUE TITLE
Remove battery level from location / location update API

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#336]
It's a privacy concern and there's no meaningful reason for it to be present.
Also to be removed from the underlying messages sent over Ably.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-862) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
I'm closing this issue since the linked PR is already merged
