### ISSUE TITLE
Information about using SDK as a dependency in Gradle

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-android#348]
We provide Ably Asset Tracking SDK as a package via Github, but we don't show how to add it as a dependency in Gradle.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-899) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
In https://github.com/ably/ably-asset-tracking-android/pull/367 I added [this section](https://github.com/ably/ably-asset-tracking-android#maven--gradle-dependencies) to the root readme.

@AndyNicks / @kavalerov - could that be enough, for now?

Once we implement https://github.com/ably/ably-asset-tracking-android/issues/318 then perhaps that can expand.

**Comment by kavalerov** [comment]
I would prefer to have at least links to Github documentation on how to use packages. It is not obvious, and if we can direct people in the right direction I think it will save them a lot of time.

**Comment by paddybyers** [comment]
Shouldn't we just include the specific dependency to add, eg as in https://github.com/ably/ably-java/blob/main/README.md#installation ?
