### ISSUE TITLE
Move to Kotlin DSL for Gradle

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#350]
Looking at [What's new in Gradle 7.0](https://gradle.org/whats-new/gradle-7/), I get the definite impression that Gradle are now encouraging developers to move away from Groovy and towards Kotlin.

I see this as something we would want to do before https://github.com/ably/ably-asset-tracking-android/issues/349.

Also acknowledging @ben-xD's comment [here](https://github.com/ably/ably-asset-tracking-android/issues/8#issuecomment-826988605).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-902) by [Unito](https://www.unito.io)

**Comment by ikbalkaya** [comment]
> Another consideration with multi-project builds is that you won’t be able to use type-safe accessors when configuring subprojects within the root build script or with other forms of cross configuration between projects. We discuss both topics in more detail in the following sections.

https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:multi_project_builds

**Comment by ikbalkaya** [comment]
I think I will have to park this work for now as it ended up taking up lots of my time. Some notes:

* Migration guides are quite optimistic and do warn little about issues you might have to deal with. I used  https://developer.android.com/studio/build/migrate-to-kts and https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html. It was easy to convert individual submodules' build.gradle files to KTS
* It's not possible to apply from a custom Gradle script file using `apply{from....` The recommended approach is using `plugins` block on root project or subproject level `build.gradle` files. I tried with a clean root level `build.gradle` file and attempted to configure JoCoCo plugin using this https://docs.gradle.org/current/userguide/jacoco_plugin.html with no luck. If that was possible I could at least configure JaCoCo and maven-publish plugins on root level `build.gradle` file.
* It's not possible to set multiproject configuration on root level with "type safe accessors" which makes IDE completely useless. From https://docs.gradle.org/current/userguide/kotlin_dsl.html. Eventually we could move those android blocks to individual modules. I had tried with some with IDE complaining, so I stopped the process.

* I had to invalidate caches / restart several times for IDE to properly detect my changes. I also had to clean Gradle caches on my system several times as a change would produce different output each time.
* Restriction for `apply {from` some custom gradle script is temporary and support will come with later releases (I couldn't find the exact link in the time of this writing)

Based on all of this I thought it's best (for now) to park this work and wait for some more complete APIs and tooling support. I eventually depend on the IDE support when writing those and that was one of the most argument for conversion. It also ended up being quite a daunty task and I felt like the tooling is not quite yet ready for this. 
What do you think @QuintinWillison ?

**Comment by QuintinWillison** [comment]
Fair enough. I trust your analysis.

@KacperKluka, have you got any further thoughts to add?

We'll keep this issue open but I'll apply [the new `blocked-by-external` label](https://github.com/ably/ably-asset-tracking-android/labels/blocked-by-external) that I just created for this issue. 😄

**Comment by ikbalkaya** [comment]
It might be also worth to say that https://github.com/ably/ably-asset-tracking-android/issues/269 will stay blocked until this one is done. 

In the meantime, I will try to convert gradle files on my own demo project and play with different ideas. I don't expect to have any issues there since it's a simple one.

**Comment by QuintinWillison** [comment]
Give we decided to give up on https://github.com/ably/ably-asset-tracking-android/pull/494, I don't see any value in keeping this issue alive. We may as well persist with Groovy. It works and is clearly the most supported route by Gradle.
