### ISSUE TITLE
Validate that trip start and end events can be seen in the dev console

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#376]
As specified by the acceptance criteria in #374, validating the work done in #357.

As an **additional acceptance criteria** for work on this retroactive issue, please add a section to the readme detailing what these events convey and how they can be viewed.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-929) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Won't do it because of https://github.com/ably/ably-asset-tracking-android/issues/431
