### ISSUE TITLE
Add matrix testing to emulate workflow

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#378]
Must include existing level we test (24) and 21.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-950) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Matrix testing was included in the PR https://github.com/ably/ably-asset-tracking-android/pull/419 which aimed to resolve the issue https://github.com/ably/ably-asset-tracking-android/issues/334. However, we've chosen API levels 24, 27 and 29 but I think that we should also add level 21.
@QuintinWillison do you think that we should add a fourth API level to the matrix or maybe replace one (preferably 27) with the new one?

**Comment by QuintinWillison** [comment]
The more levels we test the better.

The goal needs to be to ensure we're testing the 'edges' where there may be risks of things breaking or perhaps not being available at runtime. The point of this testing is to give us as much confidence as we can gain that our product will function on different Android runtime versions. If we can be sure that removing a level from the matrix will not reduce our confidence then that's fine, however I would want to have a concrete reason for reducing our runtime test coverage like that.

So, to directly answer your question:

> do you think that we should add a fourth API level to the matrix or maybe replace one (preferably 27) with the new one?

✔️  Increase coverage. Add a fourth API level to the matrix. 😄
