### ISSUE TITLE
EnhancedLocationUpdate timestamps do not represent real world time

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#387]
As mentioned in an [internal Slack thread](https://ably-real-time.slack.com/archives/C019X15CL2D/p1623420383068700?thread_ts=1623418610.067800&cid=C019X15CL2D), the enhanced location timestamp that we receive from Mapbox is not an actual timestamp since the epoch. All enhanced locations are driven by monotonic time which depends on the clock ticks since the device boot.

This means that the enhanced location time can vary significantly depending on the specific device the publisher is using. In terms of publisher implementation and resolution policy, it is not a problem as long as the differences or intervals between enhanced locations are persisted. But if some customer decides to use the time to track the driver location then it won't work (he could then use ably messages timestamps to get a rough estimation of the real-world time).

IMO we should at least update our documentation and mention that the time from the `EnhancedLocationUpdate` is not a real-world time but it's the time since the device boot.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1005) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
I think any timestamp we send from the publisher on the channel needs to be real-world time.

**Comment by KacperKluka** [comment]
In terms of documenting this, I'm wondering where we should put that description. That's because we have both `LocationUpdate` and `EnhancedLocationUpdate`. The first one is used for raw location updates that have a normal timestamp counted since the epoch. The second is used for the troublesome enhanced location updates. 
The issue is only with the enhanced one so it seems a good idea to put this commentary in `EnhancedLocationUpdate` docs. However, the timestamp isn't present directly in the `EnhancedLocationUpdate` object but it's in a `Location` class used in both location update classes. My guess is that developers will go and look into the `Location` class for information about timestamp and not to the `EnhancedLocationUpdate`. 
Are you okay with adding the info to the `Location` docs which will state something like "Timestamp which is counted since the epoch for LocationUpdate but for EnhancedLocationUpdate its counted since the device boot"? @QuintinWillison @AndyNicks WDYT? :wink:

**Comment by AndyNicks** [comment]
I agree with your proposal

**Comment by paddybyers** [comment]
I thought when we last discussed this we said that all timestamps should be absolute

**Comment by KacperKluka** [comment]
@paddybyers the best thing we can do is to use the current device time as the timestamp of the location when we receive it. There can be a problem with multiple location updates because we can also receive those intermediate locations from Mapbox as a part of a single enhanced location update and their time is somehow calculated in relation to each other. We could of course calculate the differences between them and adjust their timestamps too.
If that solution is good enough then we should be able to fix it :wink:
