### ISSUE TITLE
Individually document placeholders in example app codebases

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#392]
We already, very helpfully, collect all placeholders together in the source - see [here](https://github.com/ably/ably-asset-tracking-android/search?q=PLACEHOLDERS%3A).

However, these `// PLACEHOLDERS:` comments aren't technically, semantically linked to any particular symbol.

We should add a formal commentary to each placeholder symbol, explaining what it represents and what the app developer should replace it with in their codebase.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1036) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
This is done by landing https://github.com/ably/ably-asset-tracking-android/pull/429
