### ISSUE TITLE
Improve the example apps to be more production-quality ready

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#421]
We should improve our example apps by applying the best practices and making them more error-proof so they would be more "production-ready" than "as simple as possible".

We have a few different approaches to choose from:
1. Use the newest and recommended libraries for Android apps i.e. [Architecture Components](https://developer.android.com/topic/architecture) and [Android Jetpack](https://developer.android.com/jetpack). This will make the app up to speed with the newest Android development standards. However, it adds another layer of complexity that can make it harder to understand the code. Even though the aforementioned libraries are the recommended tools for building Android apps there are still many developers who don't know them and don't use them.
2. Identify all possible places in which the app may break and fix them. Currently, we've been mostly focusing on the happy paths and we weren't worrying that much about the other ones. We should analyze the code and look for places that can cause trouble and fix them.
3. Modify the way of using the SDK (publisher and subscriber) to match the possible clients use cases. We should think about possible ways in which our SDKs will be used by our customers in their applications. For instance, currently, the publisher is started when the first trackable is added and stopped when the last one is removed. So there is no case in which we have an active publisher without trackables, which will probably happen in real-world use cases. Our apps should cover as much possible use case scenarios as possible, so we can catch any problems in the early stage of development.
4. Treat the example apps as a tool for the manual QA and testing of the SDKs. We could add more options to the apps that would allow us to leverage all of the SDKs capabilities. This could then be used to check if the SDKs work and do manual QA with the app.

@AndyNicks @QuintinWillison WDYT? Which of those paths should we follow? Do you have any more suggestions and ideas?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1168) by [Unito](https://www.unito.io)

**Comment by AndyNicks** [comment]
I fully support points 2, 3, and 4. In terms of using libraries, I think we should make code simplicity a top priority for the sample applications.

**Comment by QuintinWillison** [comment]
I agree with @AndyNicks regarding point 1. We need to manage the balance as there's a cognitive load associated with adding additional, arguably-superfluous frameworks to example apps if they don't concretely enhance the illustrate of the core concepts being shown (i.e. Asset Tracking). I think this falls into the [K.I.S.S.](https://en.wikipedia.org/wiki/KISS_principle) category.

In terms of point 4, I think it would be helpful to perhaps start some documentation around how manual tests (human QA) are run - i.e. test cases.

**Comment by KacperKluka** [comment]
Thanks for your feedback :bow: To avoid creating one large PR with all changes from this issue I'm going to create issues as I'll investigate the code and find any places that would require improvements :wink:

**Comment by KacperKluka** [comment]
For the moment we are happy with the current example apps state so I'm closing this ticket.
