### ISSUE TITLE
Improve the example apps to be more production-quality ready

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#422]
We should improve our example apps by applying the best practices and making them more error proof so they would be more "production-ready" than "as simple as possible" :wink:

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1167) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Duplicates #421
