### ISSUE TITLE
Refactor the Ably wrapper to be more secure and error-proof

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#440]
There are a couple of places in which the `Ably` wrapper can be improved e.g. currently, we are modifying the `channels` list in the callback from Ably so we're mutating the state outside of the "main thread". We should fix this and look for other dangerous things and fix them too.
Another thing to consider is how to assert a consistent state for the channel during the disconnect operation. What if only leaving presence succeeded but detaching failed? Should the channel then be considered as closed or do we want to introduce some new state for it?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1226) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
We've decided that we will wait for https://github.com/ably/ably-asset-tracking-android/issues/522 to be resolved before working on this issue.

**Comment by KacperKluka** [comment]
We need to wait for https://github.com/ably/ably-asset-tracking-android/issues/660 as well because the Ably wrapper is a part of the shared code used by both the publisher and subscriber.

**Comment by davyskiba** [comment]
Investigation conclusions so far:
1. Ably java has an internal thread-safe channels map we could rely on instead of holding our own
2. once the channel enters the failed state only thing we can do with it is attach it, after which it starts operating normally
