### ISSUE TITLE
Different resolution policies for different subscribers

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#459]
As I understood, subscribers can request a specific resolution but publishers are the ultimate deciders. I understand that this is a consequence of using a single channel. Using a single channel to multiple subscribers makes perfect sense to me for messages with same frequencies. However if they are given a choice of frequency or resolution, it feels like they are subscribing to different channels. 

Also as I understood the highest resolution is picked for all subscribers at the end. All subscribers at least guarantee receiving messages at their desired resolution but usually with more frequency then they desired.

This is possibly not a big issue but I thought it might be a good idea to provide message with the request of each subscriber. This will likely complicate the publisher but at least subscribers can expect messages. 

Looking at Resolution object I can see that the only property that can be utilised here is `desiredInterval`. So the win from creating new channels for different resolution request may not be worth the cost. What do you think?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1266) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
It's a valid observation, though my understanding is that a priority has always been to optimise battery life of the device running the publisher. That is why it is important that the publisher is the ultimate arbiter of update frequency.

Also, of course, multiple channels would increase network traffic from publishers - ending up with duplicate messages being transmitted in parallel potentially. That is sub-optimal.
