### ISSUE TITLE
Refactor / simplify event queue that is implemented in CorePublisher

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#522]
There is a need to refactor the current event queue for easier maintainability.

### The idea and current implementation 
There is class called `CorePublisher` that is effectively an event queue and is processing all events using a function `sequenceEventsQueue` . Each time an event arrives, it launches a coroutine which I suppose is to not block the processing of incoming events. There is also a channel  which I suppose is there so that events are sent on it and be processed in a fair way.

There are also events that usually contains their handlers and they are objects that are passed to this queue. As event handling is usually (maybe always) asynchronous, these handlers also need to be tracked so that they are dealt with correctly.

### Issues
While the idea is very well thought out, I think the implementation makes it difficult to maintain general codebase

*  All event handling logic is in one function in `sequenceEventsQueue`. In any case where there needs to be additional events processing, this function will have to be modified.
* There are some names of classes that make reading things a bit difficult. For example, there is a `DefaultPublisher` that uses `CorePublisher`. CorePublisher is more like an event queue. So it might be renamed to something like `CoreEventQueue` There is also a class called `Request` which is an `Event`. I find that to be confusing. For me both Request and Event are generic terms and they are not necessarily related. For example I would make `Request` a `RequestEvent` to for more clarity.
* There seems to be lots of dependencies that `CorePublisher` uses that is likely adding the complexity to this class. For example `hooks` and `methods` look very generic, I will have to examine the usages to make more sense of them.

### Some  ideas on improvement
Below are some initial ideas on how to improve this structure, but please note that this is going to be an exploratory work so things might change in the future.
* Move event handling logic to a different class, Each handlers of events might have their own concrete implementation classes provided they implement a certain interface. 
* Try to reduce the number of dependencies on core class (and other classes) use Dependency injection in places where appropriate. Core class must be as small and as focused as possible. I would expect to change this class only when we change the behaviour of the queue, not an event.
* Try to represent 'work' or 'operation' logic with coroutines. This might introduce a simpler way to deal with edge cases like handling multiple handlers or dealing with result of the work. 

This  this is not a comprehensive list. I will do some experiments and note any other ideas that I could think of. Please add any recommendation that you have.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1377) by [Unito](https://www.unito.io)

**Comment by ikbalkaya** [comment]
After a bit of analysis thanks to and with help of @KacperKluka I have come with a solution which will make classes small, focused and unit testable. I will try to summarise the main idea and actors involved below.

### Worker Queue 
This is a queue that's going to enqueue and process **worker**s. It's going to use the original idea of leveraging a channel to enqueue and process, but it will use **worker**s instead of events

### Workers
We realised that event processing code uses and modifies state in a synchronous way. That was the original design to guarantee that state modification and access will be from a single thread. However there were also asynchronous pieces of works that needed executing immediately without blocking the existing queue.  Therefore I thought it was necessary to split work in a synchronous / asynchronous processing. 

```
interface Worker {
    fun doWork(): (suspend () -> WorkResult)?
}
```
`doWork` is an intentionally blocking method that returns an optional suspending  function. This suspending function, then later can be executed concurrently as there 

Here is an example on how this work could be run 
```
    suspend fun executeWork(){
        for (worker in channel){
            val asyncWork = worker.doWork()
            asyncWork?.let {
                scope.launch {
                    val asyncWorkResult = it()
                    println("asynWorkResult $asyncWorkResult")
                }
            }
        }
    }
```
Doing this abstraction gives us following
* We can add any type of worker without effecting the processing as worker interface would deal with interfacing.
* We can use sequential processing when using suspending functions. Currently, any async work result that uses callbacks could use sealed classes as result representation.  
* Some operations might be merged as result of this refactoring. For example the operations which does only have sync works and are in the same family can merge.
* Workers are independently testable

As an example of concrete worker 
```
class AddTrackableWorker(val delay:Long):Worker{
    override fun doWork(): (suspend () -> WorkResult)? {
        //do some synchronous work here and return async part
        println("Doing sync part of AddTrackableWorker")
        return {
            println("Doing async part of AddTrackableWorker")
            delay(delay)
            AddTrackableResult(delay)
        }
    }
}
```

This is the core idea. There will be other actors that acts as result handlers, event handlers but they are currently not defined.
### WorkResult
An asynchronous work result 
### ResultHandler
This is the result handler for WorkResult

Above classes will also have a generic interface and concrete implementations for higher maintainability.

**Comment by ikbalkaya** [comment]
### Work plan
In order to keep the scope of this pull requests small, we should find a way to work.
* Create a separate branch that will represent all refactor, as we do not want to merge small refactors into main branch, code can be reviewed based on latest state of refactorings
* Create a branch of the latest change and create a PR based on the change. It would be tedious to base all PRs from the main refactor branch.

**Comment by KacperKluka** [comment]
I'm reopening the issue as the work is not yet fully done :wink:
