### ISSUE TITLE
Zooming does not improve resolution: Resolution-type events does not get sent.

### ISSUE THREAD

**Issue by rdeoliv** [ably/ably-asset-tracking-android#535]
We noticed that when zooming in on the map from the JS console, a presence event get sent but the resolution does not change:

What should happen:
```
data: {"id" [...]"name":"enhanced"}

id: 1087DmXyAB4vXc@1637930988008-0
event: presence
data: {"id":"EY5X0xH9m7:2:0","clientId":"<INSERT_CLIENT_ID_HERE>","connectionId":"EY5X0xH9m7","timestamp":1637930987992,"channel":"tracking:roman","data":"{\"resolution\":{\"accuracy\":\"MINIMUM\",\"desiredInterval\":120000,\"minimumDisplacement\":10000.0},\"type\":\"SUBSCRIBER\"}","action":4}

id: 1087DmXyAB4vXc@1637930988054-0
event: message
data: {"id":"EgxaS2SC4w:13:0","clientId":"<INSERT_CLIENT_ID_HERE>","connectionId":"EgxaS2SC4w","timestamp":1637930988053,"channel":"tracking:roman","data":"{\"accuracy\":\"MAXIMUM\",\"desiredInterval\":1000,\"minimumDisplacement\":1.0}","name":"resolution"}

id: 1087DmXyAB4vXc@1637930988091-0
event: message
data: {"id" [...]"name":"enhanced"}
```

But what we get is only the first presence event:
```
id: 1087DmXyAB4vXc@1637931057159-0
event: presence
data: {"id":"0JKmD52Co7:0:0","clientId":"ably-client-side-api-calls-demo","connectionId":"0JKmD52Co7","timestamp":1637931057147,"encoding":"json","channel":"tracking:roman","data":"{\"type\":\"SUBSCRIBER\",\"resolution\":{\"accuracy\":\"HIGH\",\"desiredInterval\":1000,\"minimumDisplacement\":5}}","action":2}
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1405) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Additional context: we believe this may be due to android SDK parsing `minimumDisplacement` as an int whenever there is no decimal point present and would be solved by always parsing `minimumDisplacement` as a float.

**Comment by KacperKluka** [comment]
I've checked and our JSON parsing library is correctly parsing the data, so both `5` and `5.0` are parsed as a float value. So the issue is about something else.

**Comment by KacperKluka** [comment]
The issue is that Android is sending and receiving the presence data as a JSON string `"{ ... }"` and the JS subscriber is sending it as a JSON object `{ ... }`. 
I think that the Android SDK should at least accept JSON objects but maybe we should also be sending them as JSON objects instead of strings? WDYT @AndyNicks @QuintinWillison
