### ISSUE TITLE
Modify AddTrackableFailedWorker implementation to provide a result

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#546]
At the initial phase of refactoring, it wasn't safe to return a result and create a result handler for AddTrackableFailedWorker

Refactor doWork implementation so that it provides a work result + add a work result handler for it.

**Comment by KacperKluka** [comment]
This should be possible after the newest iteration of the worker queue is implemented in the Publisher SDK, therefore, I'm closing this issue due to https://github.com/ably/ably-asset-tracking-android/issues/781
