### ISSUE TITLE
Use mocks instead of Fakes for AddTrackableWorkerTest 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#551]
We can use mocks instead of fakes
Also unmock
private val resultCallbackFunction: ResultHandler<StateFlow<TrackableState>> = {}

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1416) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Closing as it was resolved in https://github.com/ably/ably-asset-tracking-android/pull/581
