### ISSUE TITLE
Simplify ConnectionCreatedWorker's async work 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#554]
As @KacperKluka pointed out [here](https://github.com/ably/ably-asset-tracking-android/pull/537#discussion_r764911838) 

> I think that too much is happening here, instead of returning the WorkResult I'd suggest simply returning a success or failure and then using it to perform more actions. Thanks to this you'll be, for example, able to use suspending disconnect instead of the callback-based one 😉

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1418) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Resolved in https://github.com/ably/ably-asset-tracking-android/pull/607/commits/f3b9ff164f30b601288cbdb672d6e16f9cbd96d2
