### ISSUE TITLE
Replace CorePublisher in PresenceMessageWorker 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#555]
I don't think that we should be referencing the `CorePublisher` from any worker :thinking: Wasn't the main reason behind having `WorkResultHandlers` to decouple the workers from the queue? If I understand it correctly we should create a work result handler for this worker and use the core publisher in that result handler :wink:

_Originally posted by @KacperKluka in https://github.com/ably/ably-asset-tracking-android/pull/540#discussion_r765007970_

I remember chatting about this. Core publisher is here only because it is implementing the functions that are used in this particular worker. As everything was inside the same class before refactoring, an easy way would be to define the functions as CorePublisher and use them on worker. However these functions will become part of another interface (Eg. SubscriptionEditor) and is going to replace CorePublisher as dependency. But is not part of this PR. I shall create an issue for this.

_Originally posted by @ikbalkaya in https://github.com/ably/ably-asset-tracking-android/pull/540#discussion_r766005865_

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1419) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Closing as this will be resolved in https://github.com/ably/ably-asset-tracking-android/issues/659
