### ISSUE TITLE
Use a different scope function in EventWorkerQueue

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#556]
I would choose some other scope function for this use-case, as the `apply` does not seem very idiomatic here :thinking: According to the [docs](https://kotlinlang.org/docs/scope-functions.html#apply) the `apply` function is mostly used for object configuration and here we're doing something different :wink: 

I'd either use the `let` function but with a named parameter, something like this
```suggestion
            it.event.let { event ->
                when (event) {
                    is Request<*> -> corePublisher.request(event)
                    is AdhocEvent -> corePublisher.enqueue(event)
                }
            }
```

or we can use `run` which will still use `this` as the event
```suggestion
            it.event.run {
                when (this) {
                    is Request<*> -> corePublisher.request(this)
                    is AdhocEvent -> corePublisher.enqueue(this)
                }
            }
```

_Originally posted by @KacperKluka in https://github.com/ably/ably-asset-tracking-android/pull/540#discussion_r765002404_

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1420) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
It's no longer relevant as the `event` field was removed from the `Worker` interface.
