### ISSUE TITLE
Improve test style in AddTrackableWorkerTest

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-asset-tracking-android#558]
Arised from 
Thanks but there are still a few `assertTrue()` in your tests when they should be `assertEquals`, please change them too :wink: 
Also, I think that the order of the arguments should be inverted :thinking: In the `assertEquals` the first argument is the expected value and the second one is the actual one, so in this case, it should probably be `Assert.assertEquals(resultCallbackFunction, alreadyIn.handler)` because we expect to see `resultCallbackFunction` and the `alreadyIn.handler` is the thing that we receive. It is important because then you have clear and precise assertion error messages and you don't have to wonder what's actually wrong in the test :wink:

_Originally posted by @KacperKluka in https://github.com/ably/ably-asset-tracking-android/pull/529#discussion_r766418874_

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1421) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Closing as it was resolved in https://github.com/ably/ably-asset-tracking-android/pull/582
