### ISSUE TITLE
Cycle test app: periodically record the collected data 

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-android#563]
The cycle test app has to periodically save and append collected trip data and MapBox test data to the S3 storage.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1425) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
As discussed on our today's call, the easiest way to implement this without the need of modifying the SDK would be to simply stop the publisher after some period of time and then start it again. This will introduce a small gap in locations but we are okay with that.

We've agreed that the data should be recorded every 30 minutes.
