### ISSUE TITLE
Cycle test app: UI modification

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-android#564]
The Cycle test application should have a simple user interface with 2 buttons: Start Tracking and Stop Tracking. The application must have the following settings predefined: 
1. Location source -- Phone
2. Accuracy -- Maximum
3. Desired interval -- 1000
4. Minimum displacement -- 2.0
5. Send raw location data -- On
6. Send resolution -- On 
7. Location predictions -- Off

Trackable ID has to be provided by the user at the start of the app and persisted for all future app launches.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1426) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@AndyNicks A few questions:
1. Are you sure to set the minimum displacement to 20 meters? Or have you meant 2.0 meters? :wink: 
2. What about the location predictions? Should we disable them too? :thinking: 
3. Should we use some specific client ID (for the Ably SDK) for this app?

**Comment by AndyNicks** [comment]
1. 2.0 meters please
2. It depends on rider;s profile. I guess Predictions will be switch off by default. 
3. Yes please.

**Comment by KacperKluka** [comment]
1. Okay, I've updated the issue description :wink: 
2. Right, so I'll not disable them manually for the moment.
3. I'll use the `TrackingTestApp` client ID for this app.

**Comment by AndyNicks** [comment]
The Cycle test app must also have token authentication, or use basic authentication with a specific Cycle test Ably API KEY app, which we must disable if needed.

In addition, the application must be disabled remotely. If the app is disabled, it should display an appropriate message.

**Comment by KacperKluka** [comment]
According to Mapbox we should disable predictions. I'm going to update this tasks description and disable the predictions in the code.

**Comment by KacperKluka** [comment]
As we've discussed on today's call, the ID should not be randomly generated but instead, it should be provided by the app user at the first start of the application. I'll update the task description accordingly.

**Comment by KacperKluka** [comment]
@AndyNicks I've created a new issue for the disabling and authentication thing as it feels a bit out of scope of the UI modifications https://github.com/ably/ably-asset-tracking-android/issues/577
