### ISSUE TITLE
MapBox Marker class is deprecated, consider replacing with the Annotation Plugin

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#569]
While reviewing #552, [this comment](https://github.com/ably/ably-asset-tracking-android/blob/0354b855d0c2b4b4bac7fef7da29d8026f03de15/publishing-example-app/src/main/java/com/ably/tracking/example/publisher/SetDestinationActivity.kt#L1) stood out to me:

> Mapbox has deprecated the `Marker` class and recommends using the `Annotation` Plugin but to keep things as simple as possible we're going to still use the `Marker` approach

My concern is that if the `Marker` API is deprecated that it will disappear at some MapBox update in the future. We should aim to be ahead of the curve here - so "as simple as possible" is perhaps not a strong argument when it pertains to sticking to obsolete APIs.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1434) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
You were right, we had to switch to `Annotation`s when we've migrated to Mapbox v2 :wink: I'm closing this issue as the work was done and merged in this PR https://github.com/ably/ably-asset-tracking-android/pull/574
