### ISSUE TITLE
Cycle test app: send messages about the app status

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#578]
The App has to send the message to Ably via a dedicated channel to send monitoring messages like:
- user <userID> has activated the app
- user <userID> has started/stopped a shift

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1447) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@AndyNicks @rdeoliv 
1. What should be the channel name?
2. What do you mean by `user has activated the app`? Should it be a message sent each time the app starts or maybe only when it's opened for the first time and the user has entered the trackable ID?
3. By `started/stopped a shift` you mean that the user starts tracking and stops it, right?
3. If more events are needed, please add them to the list in the issue description :bow:

**Comment by AndyNicks** [comment]
1. Ho about monitoring:tracking:<trackingID>
2. This is one time message sent when a user entered trackingID
3. Right -- Start & Stop tracking
