### ISSUE TITLE
Document how to bring in the SDKs from Maven Central 

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#597]
Follows up on the work done in #596.

We'll need to break up the current [GitHub Packages section](https://github.com/ably/ably-asset-tracking-android#github-packages) as some of it can be shared between instructions for both GitHub Packages and Maven Central.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1505) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@QuintinWillison I think that this has been resolved in the https://github.com/ably/ably-asset-tracking-android/pull/598, right? If yes then please close this issue :wink:

**Comment by QuintinWillison** [comment]
Indeed. Thanks! 😄
