### ISSUE TITLE
Write an upgrading to v 1.1.0 instruction

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-android#639]
Please write a brief instruction on what a user has to do in order to enable all of the improvements intriduced in v 1.1.0

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1597) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
If we won't get a regular version of the asset tracking profile we need to remember to include to this instruction something like:
> In order to use the newest beta version you need to add the Mapbox snapshot maven repository to your `build.gradle` file.
