### ISSUE TITLE
add a toggle in the example subsription app that would hide/show the raw locations marker on the map

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-android#649]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1621) by [Unito](https://www.unito.io)

**Comment by rdeoliv** [comment]
Can we deactivate the GPS horizontal accuracy circle on the raw GPS tracker? Since it's the same value as the normal tracker it does not add any value.

**Comment by rdeoliv** [comment]
Adding a edge case to think about: what if raw locations are not being send, how would the toggle react?

**Comment by KacperKluka** [comment]
The toggle will simply show/hide the raw marker if the raw data is available. If we don't have the raw data then the toggle will have no effect at all.
In terms of the accuracy circle, we can easily hide it, however, I'm not sure that the raw and enhanced accuracies will always be the same. I guess it depends on the internal implementation of the Mapbox SDK. Still, it's not a problem to either always hide it or add another toggle to show/hide it.
