### ISSUE TITLE
Mark backgroundTrackingNotificationProvider in the Builder as REQUIRED

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-asset-tracking-android#672]
When constructing a publisher using Builder omitting `backgroundTrackingNotificationProvider` parameter leads to
`com.ably.tracking.BuilderConfigurationIncompleteException: Some of the required builder parameters are missing`.

`backgroundTrackingNotificationProvider` should be marked as REQUIRED in the Builder doc comments and set in the example snippet in the "USAGE" section of README.md

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1944) by [Unito](https://www.unito.io)

**Comment by ikurek** [comment]
+1, I wanted to report the same issue, but not only for the notification. In the subscriber SDK, we get a generic error like this: `com.ably.tracking.BuilderConfigurationIncompleteException: Some of the required builder parameters are missing`. It would be useful for users to know which parameters are missing.
