### ISSUE TITLE
Check if the usage of runBlocking in the Mapbox wrapper is safe

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#680]
The `MapboxNavigation` class has to be run from the UI thread. That's why we've used `runBlocking` calls with the main dispatcher to switch the thread to the main one in the `Mapbox` wrapper. However, as pointed out [here](https://github.com/ably/ably-asset-tracking-android/pull/678#discussion_r889938867), it might not be safe. We should check if there's a better solution to this.

A possible solution suggested by @ikbalkaya :
As we need the `runBlocking` only to switch the thread we could replace it with `withContext()` calls instead. This would however require us to change the Mapbox wrapper methods to `suspend` ones.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1965) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
The current implementation is using `Dispatchers.Main.immediate` to post to UIThread, if we replace it with `Dispatchers.Main` the main thread gets locked. Probably under unlucky circumstances, current implementation can also enter this lock.

**Comment by davyskiba** [comment]
After a deeper investigation, I think no action is needed here. 
As described in [this](https://proandroiddev.com/how-to-deadlock-your-android-app-with-runblocking-8dab02c2624d#:~:text=This%20is%20why%20runBlocking%20with,t%20start%20the%20targeted%20code.) article linked by Ikbal `runBlocking(Dispatchers.Main)` leads to a deadlock if called from the Main thread. It happens in the example app if we change the dispatcher to `Main.`

However, this issue does not occur when an immediate dispatcher is used instead (which is explained in the article).

> This happens because runOnUiThread uses optimization by checking the current thread. If the current thread (UI thread in this case) is the same then it will execute the block of code right away. Otherwise, it will post a message to the main thread looper. Dispatchers.Main has similar optimization. It’s called Dispatchers.Main.immediate

@KacperKluka @ikbalkaya I would close this issue without any changes in the code, WDYT?
