### ISSUE TITLE
CoreLocationAnimator is not compatible with Jetpack Compose Maps

### ISSUE THREAD

**Issue by ikurek** [ably/ably-asset-tracking-android#681]
`CoreLocationAnimator` exposes a `Flow` of camera updates for Google Maps. This is intended to be used with `googleMap.animateCamera()` to achieve a smooth camera animation, and it works okay with the classic approach to Android UI (with XML maps).

[Jetpack Compose Maps](https://developers.google.com/maps/documentation/android-sdk/maps-compose) provides [two methods to interact with the map camera](https://googlemaps.github.io/android-maps-compose/maps-compose/com.google.maps.android.compose/-camera-position-state/index.html) - `animate()` and `move()`. While the `move()` method can be used with `CoreLocationAnimator`, the `animate()` method can't. The definition of `animate()` looks like this:

```kotlin
@UiThread
suspend fun animate(update: CameraUpdate, durationMs: Int = MAX_VALUE)
``` 

so the function is suspending, and according to the documentation, `will throw CancellationException if the animation does not fully complete`. However it's not possible to call a suspending function from inside the `Composable`, so a structure like this is NOT possible:

```kotlin
    GoogleMap(
        modifier = Modifier.fillMaxSize(),
        cameraPositionState = cameraPositionState
    ) {
            cameraPositionState.animate(     // <-- Can't be done because animate is suspending
                CameraUpdateFactory.newLatLngZoom(
                    mapState.cameraLatLng()!!,
                    zoomLevel
                )
            Circle(
                center = mapState.locationLatLng()!!,
                radius = mapState.location.accuracy.toDouble(),
                strokeColor = Color.Blue,
                fillColor = Color.Blue,
            )
        }
    }
```

It is possible to call `animate()` from outside of the composable, but then it's required to perform the animation in `try ... catch ...` block to catch `CancellationException`, and a lot of Coroutines has to be launched to perform a smooth animation.

It may be a good idea to rethink the UI animation approach for Compose, and maybe think about implementing an alternative solution.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1967) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
Because changing location animator camera updates behaviour introduces some UX issues described [here](https://github.com/ably/ably-asset-tracking-android/issues/683#issuecomment-1205112354), we won't change it and therefore this issue will be closed as well :wink:
