### ISSUE TITLE
SDK-UI position and camera APIs are inconsistent

### ISSUE THREAD

**Issue by ikurek** [ably/ably-asset-tracking-android#683]
Currently, SDK-UI components expose 2 instances of `Flow<Position>` that can be used to animate map UI (like markers, camera position, etc.). `CoreLocationAnimator.positionsFlow` emits around 60 position objects per second, making a smooth animation possible without any additional animation tools - users can simply update the position of desired marker. `CoreLocationAnimator.cameraPositionsFlow` behaves differently - it doesn't update that frequently and requires the underlying map to provide a separate method for animating camera movement.

The difference in behavior is not described anywhere, and the documentation doesn't include any details about how the implementations are different. Additionally, an implementation like this requires a specific way of animation from the map (see #681). I think it may be a good idea to unify the behavior and make the implementation work on all types of maps.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1969) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
I changed the `cameraPositionsFlow` to work exactly like the `positionsFlow` which means emitting 60 positions per second to create the camera movement animation. However, this introduces another problem with the map. When you move the map camera so frequently it basically blocks the ability to move the map manually. This means that during the map camera animation users are not able to move the map at all. They need to wait until the animation is finished, which is bad in terms of UX. The native map camera animation works differently as it allows you to move the camera while the animation is happening (at least that's how Google maps work).

Hence, I think that unifying those flows' behaviour would do us more harm than good :thinking: However, what I think is worth doing is describing how the flows behave. I wouldn't put it in the `LocationAnimator` as this is the generic interface and it should not describe a specific implementation. Therefore, I will put an appropriate description in both `CoreLocationAnimator` and `UPDATING` guide :wink:
