### ISSUE TITLE
Fix Java-WebSockets security issue

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#688]
We've received the below information about the SDK:
```
In Java-WebSocket less than or equal to 1.4.1, there is an Improper Validation of Certificate with Host Mismatch where WebSocketClient does not perform SSL hostname validation. This has been patched in 1.5.0.
```

This dependency is used in `ably-java`, so after https://github.com/ably/ably-java/issues/776 is resolved and a new `ably-java` SDK version is released we should update the `ably-java` version in AAT project.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2048) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
This is now ready to work on as `ably-android` [version `1.2.13` has been released](https://github.com/ably/ably-java/releases/tag/v1.2.13).
