### ISSUE TITLE
Inconsistent exception definitions for Subscriber methods

### ISSUE THREAD

**Issue by ikurek** [ably/ably-asset-tracking-android#689]
When looking at the [subscriber sample](https://github.com/ably/ably-asset-tracking-android#subscribing-sdk=), I noticed that `resolutionPreference()` method is wrapped in a `try ... catch ...` block. I've checked the definition of this method, and it looks like this:

```kotlin
/**
* Sends the preferred resolution for updates, to be requested from the remote publisher.
*
* An initial resolution may be defined from the outset of a [Subscriber]'s lifespan by using the
* [resolution][Builder.resolution] method on the [Builder] instance used to [start][Builder.start] it.
*
* Requests sent using this method will take time to propagate back to the publisher.
*
* The [handler] will be called once the request has been successfully registered with the server,
* however this does not necessarily mean that the request has been received and actioned by the publisher.
*
* @param resolution The preferred resolution or null if has no resolution preference.
*/
@JvmSynthetic
suspend fun resolutionPreference(resolution: Resolution?)
```

Theres no information about any exceptions that are expected to be thrown from this method, neither in the definition or javadoc. Other methods that are wrapped in `try ... catch ...` block in the sample use the `@Throws` annotation, like this:

```kotlin
@JvmSynthetic
@Throws(BuilderConfigurationIncompleteException::class, ConnectionException::class)
suspend fun start(): Subscriber
```

It may be a good idea to let users know if any exceptions are expected to be thrown from method like this

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2049) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
it seems that we've forgotten to add the information about exceptions to that method's javadoc, thanks for pointing that out :bow: 

About the `@Throws` annotation, it is only useful from the Java point of view, as in Kotlin there are no checked exceptions. Then there's the `@JvmSynthetic` annotation which hides the method from the Java API (the name of this annotation [could be better](https://github.com/ably/ably-asset-tracking-android/issues/711)). So if a method is annotated with `@JvmSynthetic` there's no point in adding the `@Throws` annotation, as it won't be visible in the Java API.

I've noticed that the `start()` method has both annotations which don't make sense. As this method was once a non-suspending one, my guess is that the `@Throws` annotation was there first and later when we added the `@JvmSynthetic` one we simply forgot to remove the first one. I will take care of it as a part of this issue, thanks for spotting that :wink:
