### ISSUE TITLE
EnhancedLocationUpdate equals returns true for different locations

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-asset-tracking-android#694]
The following test fails on the last assertion, which leads to unexpected behaviors when pushing `EnhancedLocationUpdate` as a part of the state through flows 

    @Test
    fun `EnhancedLocationUpdate equals returns true for different locations`() {
        val location1 = Location(
            latitude = 51.10681207262569,
            longitude = 17.03130008007454,
            altitude = 170.29998779296875,
            accuracy = 8.162f,
            bearing = 287.00354f,
            speed = 0.0f,
            time = 1655893534483
        )

        val location2 = Location(
            latitude = 51.10680583884444,
            longitude = 17.031332547685224,
            altitude = 170.29998779296875,
            accuracy = 8.162f,
            bearing = 287.00354f,
            speed = 0.0f,
            time = 1655893533482
        )

        val locationUpdate1 =
            EnhancedLocationUpdate(location1, listOf(), listOf(), LocationUpdateType.ACTUAL)
        val locationUpdate2 = EnhancedLocationUpdate(
            location2, listOf(), listOf(), LocationUpdateType.ACTUAL
        )

        assertTrue(location1 != location2)
        assertTrue(locationUpdate1 != locationUpdate2)
    }

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2082) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
From [this calculator](https://www.omnicalculator.com/other/latitude-longitude-distance):

<img width="478" alt="Screenshot 2022-06-22 at 13 10 36" src="https://user-images.githubusercontent.com/8318344/175025820-06340ecf-9467-4ade-8813-d03fe02db93e.png">

So, I'm guessing this could relate to the level of precision at which we're comparing floating point numbers:

- latitude difference: 0.00000623378125
- longitude difference: 0.000032467610684

Assuming we're ignoring the `time` field (I had a vague memory we were for compare), as that also has a difference.
