### ISSUE TITLE
Request new auth token when channel attach fails due to permission failure

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#695]
Only for client instances which are using token auth, not basic auth...

When an operation fails against the embedded `AblyRealtime` instance that is indicative of a service-side permissions issue (i.e. capability to perform the operation against the Ably channel is denied) then the SDK should request a new auth token.

We definitely need this for publishers.

We need to investigate whether this needs to also be implemented for subscribers.

See [this Slack comment (internal)](https://ably-real-time.slack.com/archives/C01QU436CSZ/p1655900418554909?thread_ts=1655884714.683019&cid=C01QU436CSZ) for the recorded Zoom discussion between @paddybyers, @KacperKluka, @ikbalkaya, @AndyNicks, @stmoreau and myself. It covers the reasons for taking this approach, plus how it might intersect with a future engineering effort to add an API that would allow a new auth token to be supplied to the publisher instance on addition or removal of a trackable.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2084) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
See also: https://github.com/ably/ably-asset-tracking-swift/issues/311#issuecomment-1163289516

**Comment by lawrence-forooghian** [comment]
Looks like the Android implementation has done it for both publishers and subscribers, so I’ll copy that.
