### ISSUE TITLE
Lint Gradle Groovy scripts

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#8]
See [this comment](https://github.com/ably/ably-asset-tracking-android/pull/7#issuecomment-730409672).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-817) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Or convert them to Kotlin, which might make them easier to maintain in Android Studio. 🤔 

CC @ben-xD, as this overlaps with the conversation you and I had earlier today. 😁

**Comment by ben-xD** [comment]
I'm not sure if switching to Kotlin will provide improved linting for build.gradle files, but the built in Android Studio linter is much more helpful when using the Kotlin DSL for Gradle.

**Comment by QuintinWillison** [comment]
Closing this issue as will end up superseded by https://github.com/ably/ably-asset-tracking-android/issues/350.
