### ISSUE TITLE
NPE from ably-java SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#809]
We've observed exceptions that seem to be coming from the `ably-java` SDK. This is strange because when analyzing the error trace I could not find any usage of the `PresenceMessage.clone()` method in the mentioned files. We should investigate it and decide whether that's an AAT issue or an `ably-java` issue.

```
Exception: io.ably.lib.types.AblyException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.ably.lib.types.PresenceMessage.clone()' on a null object reference
       at io.ably.lib.transport.ConnectionManager.onMessage(ConnectionManager.java:1159)
       at io.ably.lib.transport.WebSocketTransport$WsClient.onMessage(WebSocketTransport.java:183)
       at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
       at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:959)
       at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:912)
       at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
       at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by ikbalkaya** [comment]
Before trying to fix this I think we should add [ Leak canary](https://square.github.io/leakcanary/) to the project.

**Comment by davyskiba** [comment]
I think this crash can occur only in [Presence.endSync method in ably-java](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/Presence.java#L1180).
Which is called in [Presence.endSyncAndEmitLeaves()](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/Presence.java#L314)
which can be called in `Presence.setPresence` [here](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/Presence.java#L391) and [here](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/Presence.java#L431).
which is called [Channel.onPresence](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L813) or in [ChannelBase.onSync](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L1283)
both are called in [ChannelBase.onChannelMessage](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L1280)
which is called in [AblyRealtime.onMessage](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/realtime/AblyRealtime.java#L223) 
which is called in [ConnectionManager.onChannelMessage](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L1169)
which is called in `ConnectionManager.onMessage` either [here](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L1129) or [here](https://github.com/ably/ably-java/blob/2775178075de882d6184b3ad46a8fa2707ec48f5/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L1154) as both would match the stack trace we got from DH

**Comment by QuintinWillison** [comment]
The proposed fix for this issue has been released for the underlying, core SDK: https://github.com/ably/ably-java/releases/tag/v1.2.21
