### ISSUE TITLE
Memory leak connected to the Mapbox SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-android#810]
We've got informed about a memory leak when using the Publisher SDK. We should investigate whether that's AAT or Mapbox issue. Below you can find the error log with all private information removed.

```
┬───
│ GC Root: Global variable in native code
│
├─ com.mapbox.navigation.core.accounts.
│  BillingController$$ExternalSyntheticLambda2 instance
│    Leaking: UNKNOWN
│    Retaining 14.6 kB in 559 objects
│    ↓ BillingController$$ExternalSyntheticLambda2.f$0
│                                                  ~~~
├─ com.mapbox.navigation.core.accounts.BillingController instance
│    Leaking: UNKNOWN
│    Retaining 14.6 kB in 558 objects
│    ↓ BillingController.tripSession
│                        ~~~~~~~~~~~
├─ com.mapbox.navigation.core.trip.session.MapboxTripSession instance
│    Leaking: UNKNOWN
│    Retaining 14.4 kB in 543 objects
│    ↓ MapboxTripSession.tripService
│                        ~~~~~~~~~~~
├─ com.mapbox.navigation.core.trip.service.MapboxTripService instance
│    Leaking: UNKNOWN
│    Retaining 12.7 kB in 449 objects
│    ↓ MapboxTripService.tripNotification
│                        ~~~~~~~~~~~~~~~~
├─ com.ably.tracking.publisher.MapboxTripNotification instance
│    Leaking: UNKNOWN
│    Retaining 12.4 kB in 434 objects
│    ↓ MapboxTripNotification.notificationProvider
│                             ~~~~~~~~~~~~~~~~~~~~
├─ xxx.xxx.ably.PublisherService$createPublisher$6 instance
│    Leaking: UNKNOWN
│    Retaining 12.3 kB in 433 objects
│    Anonymous class implementing com.ably.tracking.publisher.
│    PublisherNotificationProvider
│    this$0 instance of xxx.xxx.ably.PublisherService
│    ↓ PublisherService$createPublisher$6.this$0
│                                         ~~~~~~
╰→ xxx.xxx.ably.PublisherService instance
     Leaking: YES (ObjectWatcher was watching this because xxx.xxx.ably.PublisherService 
     received Service#onDestroy() callback and Service not held by ActivityThread)
     Retaining 12.3 kB in 432 objects
     watchDurationMillis = 29325
     retainedDurationMillis = 23891
```

**Comment by ikbalkaya** [comment]
Before trying to fix this I think we should add [ Leak canary](https://square.github.io/leakcanary/) to the project.

**Comment by ikbalkaya** [comment]
@KacperKluka I was checking how `LeakCanary` works. Apparently leaks are categorized under 'library leaks' or 'application leaks', however I haven't seen any mention of that on the logs provided. Particularly if they own and manage  `xxx.xxx.ably.PublisherService instance` and if this leaks it will also retain references of our library and mapbox library. Just to confirm, we do not expose a foreground service as part of our SDK right?

**Comment by ikbalkaya** [comment]
I'm pausing this until we get more data from our customers

**Comment by KacperKluka** [comment]
> Just to confirm, we do not expose a foreground service as part of our SDK right?

Right, but we do use Mapbox's foreground service for the navigation logic.

The customer owns and manages the `PublisherService` instance and AFAIK they are properly stopping and destroying it 🤔

**Comment by ikbalkaya** [comment]
> The customer owns and manages the PublisherService instance and AFAIK they are properly stopping and destroying it

Famous last words 😄 I think we should ask them - especially if the category of the link is their application it means they need to do something to fix the issue. 

My understanding with service leaks is that they are like activity leaks. So for example if there is a strong reference to service somewhere after the service is shutdown/destroyed through lifecycles the service instance is still retained.  So as result, I think we should ask these two questions.
* What's the category of the leak. Is it a library leak or an application leak?
* If it's latter, did they check that they don't have a strong reference to service instances after the service has been stopped/destroyed?

**Comment by ikbalkaya** [comment]
> Right, but we do use Mapbox's foreground service for the navigation logic.

If this is created through the Publisher service it's still possible that publisher service is leaking it, but we cannot know for sure until we get a bit more information. I am not sure whether we can ask for their code that interacts with the service in order to replicate this issue.
