### ISSUE TITLE
Subscriber, upon losing connectivity, continues to show the Publisher as online

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#833]
The connectivity loss is being correctly reflected in the trackable state, which does become 'offline', however the publisher presence remains indicated as 'online'.

The fix for this bug _might_ be in the underlying [core `ably-android` SDK](https://github.com/ably/ably-java/), with the working theory being that it is not sending a "presence leave" event for presence members in this scenario, therefore leaving the disconnected AAT Subscriber thinking that the publisher is online (based on presence events only). We need to look at our features spec and see if the client library SDK behaviour is defined in relation to whether SDKs should emit "leave" events for presence members when the Ably connection has been lost. We can then decide what to do next.

Plenty of conversation on this issue in [this Slack thread (internal)](https://ably-real-time.slack.com/archives/C01QU436CSZ/p1666278420602919).

**Comment by QuintinWillison** [comment]
Sync'd with this Jira bug: [`SDK-3171` (internal)](https://ably.atlassian.net/browse/SDK-3171).

**Comment by paddybyers** [comment]
From our discussion, this is the relevant spec item: https://sdk.ably.com/builds/ably/specification/main/features/#RTP5f

If a subscriber loses connectivity and enters the `suspended` state, then it will not emit `leave` events for any presence members that were present at the time. The new presence state of all members will be reconciled on reconnection.
