### ISSUE TITLE
Publisher crashes when location data has NaN value

### ISSUE THREAD

**Issue by davyskiba** [ably/ably-asset-tracking-android#861]
Publisher SDK is crashing during location update serialization when one of the floating point fields is a `NaN.` This applies to both raw and enhanced location updates, as they share the Gson configuration. 

We should consider both sanitizing those values (i.e. using [isFinite](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/is-finite.html)) and adding better error handling to the whole WorkerQueue as mentioned in #830 

In the last log, we have seen before the crash, the velocity is a `NaN`:
> Thu Dec 22 2022 12:44:15 GMT+0530 (India Standard Time) | 22-12-22 02:14:16.682: [g] Raw location received from Mapbox: Location[fused -12.112655,-77.026313 hAcc=5 et=+19h2m32s514ms alt=156.59999084472656 vel=NaN vAcc=9 sAcc=??? bAcc=???]

The exception stack trace:
> Fatal Exception: java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
       at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:402)
       at com.google.gson.Gson$2.write(Gson.java:394)
       at com.google.gson.Gson$2.write(Gson.java:380)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
       at com.google.gson.Gson.toJson(Gson.java:747)
       at com.google.gson.Gson.toJson(Gson.java:726)
       at com.google.gson.Gson.toJson(Gson.java:681)
       at com.google.gson.Gson.toJson(Gson.java:661)
       at com.ably.tracking.common.message.MessageMappersKt.toMessageJson(MessageMappers.kt:55)
       at com.ably.tracking.common.DefaultAbly.sendEnhancedLocation(Ably.kt:517)
       at com.ably.tracking.publisher.DefaultCorePublisher.sendEnhancedLocationUpdate(CorePublisher.kt:324)
       at com.ably.tracking.publisher.DefaultCorePublisher.processEnhancedLocationUpdate(CorePublisher.kt:295)
       at com.ably.tracking.publisher.workerqueue.workers.EnhancedLocationChangedWorker.doWork(EnhancedLocationChangedWorker.kt:26)
       at com.ably.tracking.publisher.workerqueue.DefaultWorkerQueue.execute(DefaultWorkerQueue.kt:51)
       at com.ably.tracking.publisher.workerqueue.DefaultWorkerQueue.executeWorkers(DefaultWorkerQueue.kt:34)
       at com.ably.tracking.publisher.workerqueue.DefaultWorkerQueue.access$executeWorkers(DefaultWorkerQueue.kt:17)
       at com.ably.tracking.publisher.workerqueue.DefaultWorkerQueue$executeWorkers$1.invokeSuspend(DefaultWorkerQueue.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by mschristensen** [comment]
I spent a bit of time looking into this, but I'm not a Kotlin dev and I have minimal knowledge of the AAT SDK, so unfortunately my ability to help is quite limited.

However it seems to me that the simplest fix might be to change L255 of `common/src/main/java/com/ably/tracking/common/Ably.kt`:

```kt
private val gson = Gson()
```

becomes:

```kt
private val gson = GsonBuilder().serializeSpecialFloatingPointValues().create()
```

This will successfully serialise messages with NaNs into JSON like:

```json
{"location":{"type":"Feature","geometry":{"type":"Point","coordinates":[NaN,NaN,NaN]},"properties":{"accuracyHorizontal":NaN,"bearing":NaN,"speed":NaN,"time":0.0}},"skippedLocations":[]}
```

I haven't had a chance to look further into whether this is then handled correctly by any subsequent deserialisation.

**Comment by paddybyers** [comment]
See my Slack comment (https://ably-real-time.slack.com/archives/C01EPJENRD0/p1671707582344089?thread_ts=1671705435.340189&cid=C01EPJENRD0):

> Why does this then propagate to the extent that it's a crash?

and @davyskiba replied:

> Based on https://github.com/ably/ably-asset-tracking-android/issues/830 I guess it is because it was expected that using SupervisorJob will prevent the propagation and no other exception handling was used

So ISTM that we need to look at two things here:

- ensure that no exception occurs (either by handling NaN successfully, or suppressing an attempt to do anything with the event, or the velocity, if the values are not meaningful;

- ensure we understand what exception handling process(es) are in place, whether or not we understand them, and what we expected to happen in this case.

**Comment by paddybyers** [comment]
> This will successfully serialise messages with NaNs into JSON like:

```
{"location":{"type":"Feature","geometry":{"type":"Point","coordinates":[NaN,NaN,NaN]},"properties":{"accuracyHorizontal":NaN,"bearing":NaN,"speed":NaN,"time":0.0}},"skippedLocations":[]}
```

> I haven't had a chance to look further into whether this is then handled correctly by any subsequent deserialisation.

Generating an event with meaningless values doesn't seem to be useful here.

**Comment by KacperKluka** [comment]
> ensure that no exception occurs (either by **handling NaN successfully**, or **suppressing an attempt to do anything with the event, or the velocity, if the values are not meaningful**;

Do we have any preferences here? On one hand, I wouldn't want to lose the whole location object only because one of its fields is "broken". But on the other hand, we do not support `null` values for the location fields so we would have to change the "broken" (i.e. `NaN`) value to something else, which might also cause us trouble. For example, if we change the `NaN` speed to `0` we imply that the publisher has stopped. A third option might be to add support for `null` values for locations (but I wouldn't do that personally). WDYT? @paddybyers @mschristensen @lawrence-forooghian 

> ensure we understand what exception handling process(es) are in place, whether or not we understand them, and what we expected to happen in this case.

So this is something we've overlooked when designing the AAT architecture. I don't remember whether we've assumed that we've handled all the exceptions or simply forgotten about some error paths but the current situation is that whenever an unexpected exception is thrown from the `WorkerQueue` thread, then the whole queue breaks and the Publisher/Subscriber is not operating properly. This is described in https://github.com/ably/ably-asset-tracking-android/issues/830. Should we maybe assign the `important` label to that issue too and work on it now?

**Comment by mschristensen** [comment]
@KacperKluka yeah I've been thinking about the same issue. It might be that the behaviour is different depending on which field is invalid. For example, we might decide that:

- an invalid location with a NaN lat/lng/altitude coordinate can't be rendered => discard the entire location object
- a speed, accuracy or bearing with a NaN value can be set to 0, which [is the value we use when these fields are not available](https://github.com/ably/ably-asset-tracking-android/blob/4e496a050b4da64a3c27ad436a9254ed5627f012/core-sdk/src/main/java/com/ably/tracking/LocationUpdateModels.kt#L102). Alternatively (and this is a bit ugly), we could try to preserve the value from the [last known location update](https://github.com/ably/ably-asset-tracking-android/blob/8cf7f971db22b6dd6a3e4ceabc0cc0ee87054bc5/publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt#L369) if we encounter an invalid value?
- NaN timestamp => not sure, depends on what this is used for, but probably drop the location object?

We might decide, while not ideal, that it's better to set the value to 0 and imply the publisher has stopped than to throw an exception, in the interest of quickly solving this issue. We can (and should, imo) then fix the way worker queue handles exceptions.

**Comment by KacperKluka** [comment]
Sounds good to me 👍 I'd suggest we do the location object sanitization [as soon as we receive it](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt#L356-L379), so in the `DefaultMapbox` class. It will save us some unnecessary processing if the location object turns out to be unusable. Additionally, we could set the `Nan timestamp` to the current device time as soon as we receive the location.

**Comment by paddybyers** [comment]
> This is described in #830. Should we maybe assign the `important` label to that issue too and work on it now?

I've added that label

**Comment by paddybyers** [comment]
> It might be that the behaviour is different depending on which field is invalid. For example, we might decide that:
> an invalid location with a NaN lat/lng/altitude coordinate can't be rendered => discard the entire location object

yes

>  a speed, accuracy or bearing with a NaN value can be set to 0, which [is the value we use when these fields are not available](https://github.com/ably/ably-asset-tracking-android/blob/4e496a050b4da64a3c27ad436a9254ed5627f012/core-sdk/src/main/java/com/ably/tracking/LocationUpdateModels.kt#L102).

I think we definitely want to be able to use the lat/long even if we don't have velocity or bearing. It would of course be a lot nicer to be able to indicate that the values are not known (ie explicitly not by setting them to 0), but if we can't do that, then setting them to 0 is better than not having the event.

> Alternatively (and this is a bit ugly), we could try to preserve the value from the [last known location update](https://github.com/ably/ably-asset-tracking-android/blob/8cf7f971db22b6dd6a3e4ceabc0cc0ee87054bc5/publishing-sdk/src/main/java/com/ably/tracking/publisher/CorePublisher.kt#L369) if we encounter an invalid value?

Since there's no way to indicate that this is an estimated/interpolated value, then I don't think we should include it. The recipient is also able to do some prediction/interpolation based on past values.

> NaN timestamp => not sure, depends on what this is used for, but probably drop the location object?

Yes, I think a missing timestamp is fatal. It doesn't seem to be as likely we'd get a NaN for timestamp.

> We might decide, while not ideal, that it's better to set the value to 0 and imply the publisher has stopped

I don't think one erroneous value is a good basis to decide that the publisher has stopped.

**Comment by mschristensen** [comment]
> Yes, I think a missing timestamp is fatal. It doesn't seem to be as likely we'd get a NaN for timestamp.

Turns out the timestamp isn't a floating point number so can't be NaN, but we'll handle the error case where it's zero instead (uninitialised) by dropping the location object

**Comment by deanna-lad** [comment]
The link to the corresponding Jira issue is https://ably.atlassian.net/browse/SDK-3197
