### ISSUE TITLE
Adding trackable just before fallback reconnection results in multiple exceptions

### ISSUE THREAD

**Issue by lmars** [ably/ably-asset-tracking-android#863]
When a trackable is added, an ATTACH operation is performed on the underlying channel. If this ATTACH request occurs just before the underlying WebSocket connection closes and is then re-established to a fallback endpoint, multiple exceptions can occur and the trackable marked as failed.

For example, from log `redacted_9f8f02504a8b9549f7ccc905feff5a73_error_session_639E5F0300AD00014C5698B3802296F3_DNE_5_v2.log`:

- a trackable is added with ID `tracking:bo:22577803`:

```
17-12-22 21:01:15.506: [j] Publisher track operation started
17-12-22 21:01:15.508: zo0.b: RealtimeChannel(); channel = tracking:bo:22577803
17-12-22 21:01:15.511: zo0.b: enter(); channel = tracking:bo:22577803
17-12-22 21:01:15.511: zo0.b: update(); channel = tracking:bo:22577803
17-12-22 21:01:15.512: zo0.b: attach(); channel = tracking:bo:22577803
17-12-22 21:01:15.513: zo0.b: attach(); channel = tracking:bo:22577803; sending ATTACH request
17-12-22 21:01:15.513: zo0.b: setState(): channel = tracking:bo:22577803; setting attaching
17-12-22 21:01:15.521: io.ably.lib.transport.WebSocketTransport: send(); action = attach
17-12-22 21:01:15.524: io.ably.lib.transport.WebSocketTransport: send(): attach: {"action":10,"channel":"tracking:bo:22577803","count":0,"flags":720896,"timestamp":0}
```

- the WebSocket connection closes shortly afterwards:

```
17-12-22 21:01:15.791: io.ably.lib.transport.WebSocketTransport: onClose(): wsCode = 1000; wsReason = ; remote = true
```

- the connection is re-established to a fallback endpoint 3s later (although the CONNECTED event comes with an error):

```
17-12-22 21:01:18.409: io.ably.lib.transport.b: onMessage() (transport = io.ably.lib.transport.WebSocketTransport {wss://<redacted>-c-fallback.ably-realtime.com:443/?accessToken=<redacted>&v=1.0&format=msgpack&resume=e7dCdpyiQBJGeW%216DQ1MPRqrvqqC4of-ae7a&connectionSerial=4&clientId=bo-315974&heartbeats=false&agent=ably-java%2F1.2.20%20ably-asset-tracking-android%2F1.5.1%20android%2F30}): connected: {"action":4,"connectionDetails":{"clientId":"bo-315974","connectionKey":"a2dvt-5bABJFtd!Th2Ffc0O2lMqcBQ7-1ea2a","connectionStateTtl":120000,"maxFrameSize":262144,"maxIdleInterval":15000,"maxInboundRate":100,"maxMessageSize":65536,"maxOutboundRate":100,"serverId":"frontend.6bc1.5.ap-southeast-1-A.i-0007e84b9e981658b.a2dvt-5bABJFtd"},"connectionId":"Th2Ffc0O2l","connectionSerial":-1,"count":0,"error":{"code":80008,"href":"https://help.ably.io/error/80008","message":"Unable to recover connection: not found (6DQ1MPRqrvqqC4of). (See https://help.ably.io/error/80008 for help.)","statusCode":400},"flags":0,"timestamp":0}
```

- the channel is suspended:

```
17-12-22 21:01:18.410: zo0.b: setSuspended(); channel = tracking:bo:22577803
17-12-22 21:01:18.410: zo0.b: failQueuedMessages()
```

- the trackable is marked as failed:

```
17-12-22 21:01:18.420: [m] Failed to suspend enter presence for channel tracking:bo:22577803 s3.c: Unable to recover connection: not found (6DQ1MPRqrvqqC4of). (See https://help.ably.io/error/80008 for help.)
17-12-22 21:01:18.429: [m] Failed to connect for trackable bo:22577803 s3.c: Unable to recover connection: not found (6DQ1MPRqrvqqC4of). (See https://help.ably.io/error/80008 for help.)
17-12-22 21:01:18.431: [j] Publisher track operation failed s3.c: Unable to recover connection: not found (6DQ1MPRqrvqqC4of). (See https://help.ably.io/error/80008 for help.)
```

- the connection state is set to CONNECTED (albeit with an error reason):

```
17-12-22 21:01:18.430: io.ably.lib.transport.b: setState(): setting connected; reason {ErrorInfo message=Unable to recover connection: not found (6DQ1MPRqrvqqC4of). (See https://help.ably.io/error/80008 for help.) code=80008 statusCode=400 href=https://help.ably.io/error/80008}
```

- a DETACH request is sent:

```
17-12-22 21:01:18.431: io.ably.lib.transport.WebSocketTransport: send(); action = detach
io.ably.lib.transport.WebSocketTransport: send(): detach: {"action":12,"channel":"tracking:bo:22577803","count":0,"flags":0,"timestamp":0}
```

- the app attempts to add the trackable again:

```
17-12-22 21:01:18.455: [j] Publisher track operation started
17-12-22 21:01:18.456: zo0.b: RealtimeChannel(); channel = tracking:bo:22577803
17-12-22 21:01:18.457: zo0.b: enter(); channel = tracking:bo:22577803
17-12-22 21:01:18.457: zo0.b: update(); channel = tracking:bo:22577803
17-12-22 21:01:18.457: zo0.b: attach(); channel = tracking:bo:22577803
17-12-22 21:01:18.458: zo0.b: attach(); channel = tracking:bo:22577803; sending ATTACH request
17-12-22 21:01:18.458: zo0.b: setState(): channel = tracking:bo:22577803; setting attaching
17-12-22 21:01:18.458: io.ably.lib.transport.WebSocketTransport: send(); action = attach
17-12-22 21:01:18.458: io.ably.lib.transport.WebSocketTransport: send(): attach: {"action":10,"channel":"tracking:bo:22577803","count":0,"flags":720896,"timestamp":0}
```

- Ably acknowledges the previous DETACH request:

```
17-12-22 21:01:19.035: io.ably.lib.transport.b: onMessage() (transport = io.ably.lib.transport.WebSocketTransport {wss://<redacted>-c-fallback.ably-realtime.com:443/?accessToken=<redacted>&v=1.0&format=msgpack&resume=e7dCdpyiQBJGeW%216DQ1MPRqrvqqC4of-ae7a&connectionSerial=4&clientId=bo-315974&heartbeats=false&agent=ably-java%2F1.2.20%20ably-asset-tracking-android%2F1.5.1%20android%2F30}): detached: {"action":13,"channel":"tracking:bo:22577803","count":0,"flags":0,"timestamp":0}
```

- the channel is suspended again:

```
17-12-22 21:01:19.035: zo0.b: Server initiated detach for channel tracking:bo:22577803 whilst attaching; moving to suspended
```

- the trackable is marked as failed:

```
17-12-22 21:01:19.037: [m] Failed to suspend enter presence for channel tracking:bo:22577803 s3.c: Unknown error when entering presence tracking:bo:22577803
17-12-22 21:01:19.046: [j] Publisher track operation failed s3.c: Unknown error when entering presence tracking:bo:22577803
```

---

So, there are two issues here:

1. after falling back to another region, the "Unable to recover connection: not found" error reason is being treated as fatal and preventing the trackable from being added, even though it's come in a CONNECTED event.
2. there's a race between a previous DETACH being acknowledged, and an ATTACH being retried, which leads to the ATTACH being rejected and the channel suspended

**Comment by ikbalkaya** [comment]
As far as I can see, this is an issue with ably-java rather than asset tracking library.  Error for trackable failure comes from `onError` callback from presence.`enter`. I think this is to do with presence.enter callback not handling connection recovery as it is expected. I will check Java code and see if I can see any hints on that.

For attach - detach race condition, this also sounds like an SDK issue. @lmars do you know by any chance if we are supposed to maintain some sort of ordering for these kind of operations on SDKs? For example, are we supposed to discard the next DETACH response if an ATTACH request is sent? Because if we don't, to me this will be inevitable.

**Comment by lmars** [comment]
> do you know by any chance if we are supposed to maintain some sort of ordering for these kind of operations on SDKs?

I don't know if it's in the spec or anything, but if I as a user of the SDK call `channel.detach`, then subsequently call `channel.attach`, I'd expect the channel to eventually re-attach, rather than the channel becoming suspended because I tried to re-attach too quickly (i.e. before the detach was acknowledged).

**Comment by paddybyers** [comment]
> do you know by any chance if we are supposed to maintain some sort of ordering for these kind of operations on SDKs? For example, are we supposed to discard the next DETACH response if an ATTACH request is sent? Because if we don't, to me this will be inevitable.

The spec says:
https://sdk.ably.com/builds/ably/specification/main/features/#RTL4h
https://sdk.ably.com/builds/ably/specification/main/features/#RTL5i

**Comment by ikbalkaya** [comment]
I have created to separate issues on ably-java and will work on them separately 
https://github.com/ably/ably-java/issues/884
https://github.com/ably/ably-java/issues/885

**Comment by paddybyers** [comment]
> the channel is suspended
Do we know why this happened? Is this something AAT did, or something ably-java did?

**Comment by ikbalkaya** [comment]
> Do we know why this happened? Is this something AAT did, or something ably-java did?

This is from ably-java (Log is from https://github.com/ably/ably-java/blob/f9e491999b194a6ad250c003ce1202e56eede080/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L587)
