### ISSUE TITLE
Adding a trackable stalls forever if presence.enter() is interrupted by a disconnection

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-asset-tracking-android#896]
This behaviour has been observed during analysis of integration test failures (see https://github.com/ably/ably-asset-tracking-android/issues/865).

The underlying cause is https://github.com/ably/ably-java/issues/474.

Related: https://github.com/ably/ably-asset-tracking-android/issues/862

**Comment by AndyTWF** [comment]
This possibly may be the underlying cause of the timeout issues in the flakey test at https://github.com/ably/ably-asset-tracking-android/issues/846 ?

**Comment by jaley** [comment]
@ikbalkaya - I believe your incoming PR to update `ably-java` will resolve this issue

**Comment by ikbalkaya** [comment]
@jaley I just had a run with tests against new changes. I'd assume that test for this case would be faultDuringTracking[DisconnectWithFailedResume] If that's the case it fixes the issue, I'll reeanble the test and create a PR on this
