### ISSUE TITLE
Exceptions thrown inside a block passed to `DefaultAbly`’s `scope.launch()` are suppressed

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-android#909]
See 4430c3527b70fa8649cba99501dde2cb84330e13 which demonstrates this issue. The part that worries me is in bold.

> I have modified the code so that the test "connect - when channel attach does not complete" will cause line 374 of Ably.kt to throw an exception.
> 
> When running this test, a message is logged (presumably by the coroutines runtime) about the caught exception, but it does not seem to propagate any further and the test passes.
> 
> This issue only occurs when I throw the exception inside the `scope.launch` block - if I call it outside that block then the exception propagates and the test fails.
> 
> I guess this is related to the fact that `scope` uses `SupervisorJob`, which I believe introduces some sort of error suppression behaviour. I don’t know whether this is intentional, perhaps so that unexpected errors don’t bring the whole process down? **But in unit tests, it has the nasty side effect of causing MockK’s fail-fast mocks – which rely on exceptions to communicate the fact that they have been incorrectly configured (i.e. that a called method has not been mocked) – to not cause a test failure when incorrectly configured. This can lead to incorrectly passing tests.**

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-3247
