### ISSUE TITLE
Retry behaviour improvements for Ably API calls

### ISSUE THREAD

**Issue by jaley** [ably/ably-asset-tracking-android#927]
`Publisher` does not currently retry in all circumstances that we need it to retry. We should design and implement a retry mechanism that causes the following behaviour:

### Connections

* Connection retry attempts are handled indefinitely by `ably-java` - there's no need to retry these in AAT
* Simply allow `ably-java` to continue to attempt connection until it succeeds, as per its own retry policies
* Use the state change listener to check for a fatal error (e.g. invalid credentials). There will be a `4xx` status code for fatal errors.

### Channel Attachments

* Similarly to connections, `ably-java` will perform retries automatically
* Just listen for fatal errors so that we correctly move to `Failed` state when these happens

### Presence

* `enter()`
  * Check callbacks, if you get a `5xx` error, schedule retry for 15 seconds later.
  * If you get a `4xx`, move to failed state, detach from channel and, if this is the last trackable, close connection 
  * Continue retrying on `5xx` errors indefinitely
  * Note that the presence data (resolution preference) may change between retries
* `leave()`
  * Give leave a total 30s time limit to complete successfully
  * If you get a, `onError` callback within that 30 seconds, check the error code:
    * If it's a `5xx`, schedule a retry in 15 seconds (this doesn't restart overall timeout)
    * If it's a`4xx`, give up, detach and disconnect if final trackable
  * If 30s expire, give up, detach and disconnect if final trackable

To relate these back to the `Publisher` APIs:

* `start()`
  * Triggers connection to Ably (TBC?)
  * Should return immediately and follow normal connection retry policy above in background, as connectivity state is expected to vary during normal operation
* `Publisher.track()` and `Publisher.add()`:
  * Trigger connection (if not connected), channel attachment, and presence enter
  * Should return immediately and handle all of this in the background, as per retry policies above
  * `TrackableState` used to check current status
* `Publisher.remove()`
  * Triggers presence leave, channel detach, disconnect if final trackable
  * Should return immediately and let the channel/presence cleanup and retry behaviours above happen in background
  * `StateFlow<TrackableState>` change should also be immediate
* `Publisher.stop()`
  * Similar to `remove()` (?)

@paddybyers , @KacperKluka  -- initial retry behaviour spec to review

**Comment by jaley** [comment]
> we would need to manually set the trackable state to Offline

Does removing a Trackable cause it to be `Offline`? What I mean is if `remove()` returns with no error, the user should reasonably expect that Trackable to be "gone", i.e.

```kotlin
// returns immediately, no errors
publisher.remove(trackableId)

// this should be null?
assert(publisher.getTrackable(trackableId) == null)
```

**Comment by KacperKluka** [comment]
> Does removing a Trackable cause it to be `Offline`? 

It should but now that I look into the code I'm not certain that will be the case 🤔 I'll write a test to verify it. If this won't happen then I'll create an issue for that.

> What I mean is if `remove()` returns with no error, the user should reasonably expect that Trackable to be "gone", i.e.

That's true, after the `publisher.remove()` call completes the trackable is removed from the publisher's trackable set (so the call to `publisher.getTrackableState()` returns `null`).

**Comment by jaley** [comment]
I'm not so sure a removed Trackable should go to the `Offline` state? It's being removed anyway, so presumably the state is no-longer being monitored or reported to the user? What happens to the `StateFlow` when a trackable is removed? Is there some kind of close operation?

**Comment by KacperKluka** [comment]
According to the [docs](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/)
> State flow never completes.

So it looks like we can't close it. We could introduce another trackable state, something like `Removed` or `Closed` that would represent a trackable that has been removed, WDYT? 🤔

**Comment by jaley** [comment]
OK, I'm a bit confused by that. Do you recall what the design intentions were there? Or maybe @QuintinWillison does? If the user has access to `remove()`, which will effectively terminate tracking, the `StateFlow` should end at some point?

IIUC adding a state to a sealed class (like `TrackableState`) is a source-breaking change as it'll mean a previously-exhaustive `when` statement is no-longer exhaustive?

**Comment by KacperKluka** [comment]
> If the user has access to `remove()`, which will effectively terminate tracking, the `StateFlow` should end at some point?

The flow will "end" because there won't be any new states published on it. Not sure if that's good enough, but that's probably the best we can do with a `StateFlow` 🤔 

> IIUC adding a state to a sealed class (like `TrackableState`) is a source-breaking change as it'll mean a previously-exhaustive when statement is no-longer exhaustive?

True, but I'm not sure if that would be an error or just a warning 🤔

**Comment by jaley** [comment]
OK, well, let's not block the rest of the progress on this retry mechanism while we figure out the ideal semantics for `remove()`, at least. Preserving the existing behaviour and just not throwing an exception when offline will be a reasonable starting point.

**Comment by KacperKluka** [comment]
On a call with @davyskiba we decided that the most appropriate place for the retry mechanism would be the `WorkerQueue`. As there are already issues connected to the presence [`enter`](https://github.com/ably/ably-asset-tracking-android/issues/871) and [`leave`](https://github.com/ably/ably-asset-tracking-android/issues/905) operations, in this issue I will only prepare the codebase to detect whether an Ably error is fatal or retriable. Then in the other issues, we will be using this to actually implement the desired retry mechanism.
