### ISSUE TITLE
Investigate TODO comment in `DropAction` fault regarding "limit"

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-android#934]
As commented on [here](https://github.com/ably/ably-asset-tracking-android/pull/933/files#r1083957234) by @AndyTWF.

The comment might be inert or otherwise unimportant, but in the interests of getting the aforementioned pull request merged adding this issue to defer looking at this until later.

**Comment by AndyTWF** [comment]
@jaley has made a summary of the issue: https://github.com/ably/ably-asset-tracking-android/pull/933#discussion_r1083903659
